### PR TITLE
Add long click option

### PR DESCRIPTION
**Pull request by theknut**
Long pressing the play store button will copy the play store link to the
clipboard

### CODE REVIEW

**Comment by qwerty12** [comment]
Thank you for your contribution; however, I'm not really maintaining anything I made for Android currently (I don't have the Android SDK set up currently)... I think there's already another Xposed m odule that does what this one does but more. If you haven't already, please feel free to publish a build with your changes

**Comment by theknut** [comment]
A friend of mine is using your mod and asked me to implement the feature
since he can't code. So I did it, gave him my apk and opened the pull
request. I just thought about sharing it because it's actually useful.
However there is no xda thread for it so I can't publish it anyways.

I like the way you wrote the code. It looks very good and intelligent. How
come you don't code for Android anymore?
Am 19.08.2014 19:04 schrieb "Faheem Pervez" notifications@github.com:

**Comment by qwerty12** [comment]
I never wrote anything complicated anyway and I only started with Xposed because it was new back then and it seemed like a refreshing change from running baksmali etc. and re-odexing.... These days there's far better people than I making much better modules so these days I just use my Android phone enjoying the fruits of their labour :)

**Comment by theknut** [comment]
Do you use Xposed GEL Settings by any chance? It's my module ;)
Am 19.08.2014 19:23 schrieb "Faheem Pervez" notifications@github.com:

**Comment by qwerty12** [comment]
I don't, but I've heard very good things about it on the Internet ;) I'm in love with HTC's Blinkfeed and as I've turned off Google search history (at least officially...) I can't use Google Now - and without your module, that and "OK Google" integration (which doesn't appeal to me either - in Chromium I disable as much microphone functionality as I can) are all that Google's launcher is good for :/

**Comment by theknut** [comment]
Yes, that's all it is good for. If you don't use these there is no reason
for GNL.

Good talk and have a nice day!
Am 19.08.2014 23:19 schrieb "Faheem Pervez" notifications@github.com:

**Comment by qwerty12** [comment]
Likewise! Thanks again for your work and I apologise for my lateness in initially replying to you

**Pull request merged**
